[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tfs-client"
version = "0.1.6"
authors = [
    {name="Marcel Claramunt", email="marcel@moveread.com"}
]
description = "Tools to simplify access to tfserving via HTTP, specially for Moveread"
dependencies = [
    "aiohttp", "haskellian", "haskellian-iterables"
]
requires-python = ">=3.10"
readme = {file="README.md", content-type="text/markdown"}

# [project.urls]
# repo = "<GIT_REPO_URL>"
