[project]
name = "geo-skeletons"
version = "0.11.0"
description = "Easily extended way to represent structured and unstructured geophysical data."
authors = [ { name = "Jan-Victor Bj√∂rkqvist", email = "janvb@met.no" } ]
dependencies = [ "numpy", "xarray", "pandas", "utm", "geopy", "dask" ]

#[project.optional-dependencies]
#tests = [ "numpy", "xarray", "pandas", "utm", "geopy"]

[project.urls]
repository = "http://github.com/bjorkqvi/skeletons"

# [project.scripts]
# "sfydata" = "sfy.cli.sfydata:sfy"
