[project]
name = "airflow-fernet-secrets"
version = "0.0.4"
description = "airflow filesystem secret backend using fernet"
authors = [{ name = "phi", email = "phi.friday@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Apache Airflow",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.8, <3.13"
dependencies = [
    "typing-extensions>=4.4.0",
    "sqlalchemy>=1.4",
    "jsonschema",
    "pyyaml",
    "cryptography",
]

[project.optional-dependencies]
asyncio = [
    "sqlalchemy[asyncio]>=1.4",
    "aiosqlite",
]

[project.urls]
Repository = "https://github.com/phi-friday/airflow-fernet-secrets"

[tool.rye]
managed = true
dev-dependencies = [
    "apache-airflow==2.9.0",
    "ruff==0.3.7",
    "ipykernel>=6.29.4",
    "pytest>=8.1.1",
    "sqlalchemy2-stubs>=0.0.2a38",
    "anyio",
    "uvloop; platform_system != 'Windows'",
    "pre-commit>=3.5.0",
    "psycopg2>=2.9.9",
    "pyodbc>=5.1.0",
    "pymssql>=2.3.0",
]

[project.entry-points."apache_airflow_provider"]
provider_info = "airflow_fernet_secrets.info:get_provider_info"

[tool.hatch.build.targets.sdist]
exclude = ["src/**/.gitignore"]
[tool.hatch.build.targets.wheel]
packages = ["src/airflow_fernet_secrets", "src/airflow"]
artifacts = ["src/**/.gitignore"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.pyright]
include = ["src", "tests"]
pythonVersion = '3.8'
pythonPlatform = 'Linux'
diagnostic = 'basic'
