[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "arabic-datetime"
version = "0.1.1"
authors = [
  { name="Khaldevmedia", email="khaldevmedia@gmail.com" },
]
description = "A simple package for formating arabic date and time."
readme = "README.md"
requires-python = ">=3.7"
keywords = ["python", "arabic", "datetime", "date", "time", "arabic date", "arabic time", "arabic numerals", "eastern arabic numerals", "month names"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/khaldevmedia/arabic-datetime"
"Bug Tracker" = "https://github.com/khaldevmedia/arabic-datetime/issues"