[tool.poetry]
name = "nested-config"
version = "2.0.3.post0"
description = """\
Parse configuration files that include paths to other config files into Pydantic model\
 instances. Also support pathlib.PurePath on Pydantic 1.8+.\
"""
authors = ["Randall Pittman <pittmara@oregonstate.edu>"]
readme = "README.md"
license = "MIT"
repository = "https://gitlab.com/osu-nrsg/nested-config"
keywords = ["pydantic", "config", "configuration files"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Pydantic",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
include = ["CHANGELOG.md"]

[tool.poetry.urls]
Changes = "https://gitlab.com/osu-nrsg/nested-config/-/blob/master/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.8"
pydantic = ">=1.8,<3.0.0"
single-version = "^1.6.0"
tomli = {version = "^2.0.0", python = "<3.11"}
typing-extensions = "^4.6.0"
pyyaml = {version = ">=5.1.0,<7.0.0", optional = true}

[tool.poetry.group.dev.dependencies]
ipython = "^7.22.0"
ruff = "^0.3.5"
pytest = "^8.1.1"
mypy = "^1.9.0"
types-pyyaml = ">=5.1.0"

[tool.poetry.extras]
yaml = ["pyyaml"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 90

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401"]

[tool.pyright]
defineConstant = { "PYDANTIC_1" = false }  # change to true for Pydantic <2.0
