[tool.poetry]
name = "photo-gps-client"
version = "0.1.6"  # set by antonio-py-dynamic-version
description = ""
authors = ["antonio <mr.antonsilin@gmail.com>"]
readme = "README.md"
packages = [
    { include = "photo_gps"},
]

[tool.poetry.scripts]
photogps = 'photo_gps.photogps:app'

[tool.poetry.dependencies]
python = "^3.11"
pyexiftool = "^0.5.6"
colorama = "^0.4.6"
arrow = "^1.3.0"
tqdm = "^4.66.2"
pyyaml = "^6.0.1"
requests = "^2.31.0"
jinja2 = "^3.1.3"

[tool.poetry.group.dev.dependencies]
antonio-py-dynamic-version = {git = "https://bitbucket.org/asilin/antonio-py-dynamic-version.git"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
