
[project]
license = { file = "LICENSE" }
name = "qwrapper"
version = "0.1.16"
description = "A QEMU wrapper for Python"
readme = "README.md"
requires-python = ">=3.7"
authors = [{ name = "Daniel Dybing", email = "danieldy@uia.no" },
           { name = "Ali Sirvanovitsj Ismailov", email = "alisi18@uia.no"},
           { name = "SirÃ©n Elise Lund Lohre", email = "selohre@uia.no"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
