[tool.poetry]
name = "edge-orm"
version = "0.7.25"
description = ""
authors = ["Jeremy Berman <jerber@sas.upenn.edu>"]
readme = "README.md"
packages = [{ include = "edge_orm" }]
exclude = ["tests/**/*"]

[tool.poetry.dependencies]
python = "^3.11"
edgedb = '*'
#edgedb = {git = 'https://github.com/edgedb/edgedb-python.git', branch = 'describe-expect-one'}
#pydantic = {version = ">=2.0a1", allow-prereleases = true}
pydantic = { extras = ["email"], version = "^1.10" }
orjson = "^3.8.0"
devtools = "*"
black = "*"


mkdocs-material = { version = "^8.5.7", optional = true }


[tool.poetry.group.dev.dependencies]
mypy = "^0.982"
pytest = "^7.1.3"
Faker = "^15.1.1"
sentry-sdk = "^1.10.1"
pytest-asyncio = "^0.20.1"
python-dotenv = "^0.21.0"

[tool.poetry.extras]
docs = ['mkdocs-material']


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
