[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ssl_framework"
version = "0.2.2"
authors = [
  { name="Carl Schader", email="carlschader@gmail.com" },
]
description = "A framework for training self supervized learning models in PyTorch. It makes it easy to train an SSL model from scratch, on top of a pre-trained model, or add it to an existing code base."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch >= 2.0.0",
    "torchvision >= 0.17.0",
]

[project.urls]
Homepage = "https://github.com/carlschader/ssl_framework"
Issues = "https://github.com/carlschader/ssl_framework/issues"

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["."]  # ["."] by default
include = ["*"]  # ["*"] by default
exclude = ["scripts"]  # empty by default

