[tool.poetry]
name = "flops_utils"
version = "0.1.5"
description = "A library containing commong utilities for FLOps"
authors = ["Alexander Malyuk <malyuk.alexander1999@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

#[tool.poetry.scripts]
#oak = "flops_utils.main:main"

#[tool.poetry.packages]
#include = [
#    "flops_utils/*",
#]

packages = ["flops_utils/*"]


[tool.black]
line-length = 100
