[package]
name = "vizibridge"
version = "0.2.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "vizibridge"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
seq-macro = "0.3.5"
vizitig-lib = { git = "https://gitlab.inria.fr/cpaperma/vizicomp.git"  }
