[tool.poetry]
name = "netswitcher"
version = "0.2.1"
description = ""
authors = ["Fearkin <aloneWorker@yandex.ru>"]
readme = "README.md"
packages = [
    { include = "core" }
]


[tool.poetry.dependencies]
python = "^3.8"
netmiko = "^4.3.0"
typer-slim = "^0.12.3"

[tool.poetry.scripts]
nt = "core.main:create_app"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
