[tool.poetry]
name = "netlink-applog"
version = "0.0.2"
description = "Logging to a SQLite Database"
authors = ["Bernhard Radermacher <bernhard.radermacher@netlink-consulting.com>"]
repository = "https://gitlab.com/netlink_python/netlink-applog.git"
packages = [ { include = "netlink/applog" } ]


[tool.poetry.dependencies]
python = ">=3.9,<3.13"
PyPubSub = ">=4.0.3"

[tool.poetry.dev-dependencies]
black = ">=24.4.0"
pytest = ">=8.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
