[tool.poetry]
name = "spc-toolbox"
version = "0.1.1"
description = "A toolbox for Statistical Process Control"
authors = ["Philip Solarz <philip.solarz@teliacompany.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.1"
numpy = "^1.26.4"
matplotlib = "^3.8.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
