[tool.poetry]
name = "ocpy-client"
version = "1.3.13"
description = "Python client library to access the different APIs of OpenCast, tested with OC13.5."
authors = ["Tobias Kurze <it@t-kurze.de>"]
license = "GPL"
packages = [
    { include = "ocpy" },
]

[tool.poetry.dependencies]
python = ">=3.8,<4"
requests = "^2"
xmltodict = "^0"
PyYAML = "^6"
loguru = "^0"
pre-commit = "^2"
pendulum = "^2"
maya = "^0"
python-dotenv = "^1"

[tool.poetry.group.dev.dependencies]
black = "^23"
pip-audit = "^2"
pytest = "^6"
pytest-xdist = "^2"
pytest-cov = "^2"
Sphinx = "^3"
sphinx-autoapi = "^1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
