[tool.poetry]
name = "nonebot-plugin-zhichang"
version = "1.0.3"
description = "有趣的职场人专属日历"
authors = ["Priopus <360048935@qq.com>"]
readme = "README.md"
packages = [{include = "nonebot_plugin_zhichang"}]

[tool.poetry.dependencies]
python = "^3.8"
nonebot2 = "^2.0.0b2"
nonebot-adapter-onebot = "^2.0.0b1"
nonebot-plugin-apscheduler = "^0.4.0"
httpx = "^0.23.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
