[tool.poetry]
name = "thinkcol_llm_client"
version = "0.1.2"
description = "Package for calling llm clients asynchronously"
authors = ["jedric01 <jedric@connect.ust.hk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.14.2"
boto3 = "^1.34.68"
python-dotenv = "^1.0.1"


[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# static analysis
# ignore local environment site packages
[tool.black]
exclude="env/"

[tool.mypy]
exclude="env/"
ignore_missing_imports=true